---
title: "Other Indices"
bibliography: references.bib
link-citations: true
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Other Indices}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In addition to calculating the original *AMBI* index, and the
multivariate *M-AMBI*, the package allows you to calculate several other
benthic fauna indices.

## Danish indices

Development of the `ambiR` package was motivated by a need to integrate
calculation of the *AMBI* index as well as the derived *DKI* index in
analyses using R. These analyses contributed to a study investigating
trends in eutrophication status in Danish coastal waters [@JORGENSEN202613]
and necessitated calculation of the Danish quality
index DKI (Danish: *Dansk Kvalitetsindeks*) based on observations
recorded in the Danish national monitoring program

### DKI

*DKI* is essentially an adaptation of *AMBI* to Danish conditions, to account for
the lower diversity which can be expected in the more brackish waters of the
Inner Danish waters. It can only be calculated after first calculating *AMBI*,
the AZTI Marine Biotic Index, and *H'*, the Shannon diversity index.
Both of these required index values are included in output generated by
the `AMBI()` function.

$$ DKI_{v1} =  \left( \frac{ \left( 1- \frac{AMBI}{7}\right) + \left( \frac{H'}{H'_{max}} \right)}{2} \right)    * \left( \frac{\left(1- \frac{1}{N} \right) + \left(1- \frac{1}{S} \right)}{2} \right) $$
The `DKI()` function uses a maximum limit value of *H'* `H_max` in Danish waters as a
reference value to normalise *DKI*. If this value is not specified as an argument, 
then the default value is used (`5.0`), as described by @BORJA200742:

> *However, in the present exercise, the Danish method used H'~max~ (~5) as a kind of reference*

### DKI v2

The `DKI2()` function calculates an updated version of the *DKI* index which uses
empirical relationships between salinity and expected *AMBI* index and *H'* values
to adjust the *AMBI* result.
[@Carstensen201493].

$$ DKI_{v2} = \frac{1}{2} \left(  \left( 1- \frac{AMBI-AMBI_{min}}{7} \right) +  \left(\frac{H'}{H'_{max}}\right) \right) * \left(1- \frac{1}{N} \right) $$
where *H~max~* and *AMBI~min~* are functions of salinity (psu):

$$ H'_{max} = 2.117 + 0.086 * salinity,  \frac{H'}{H'_{max}} \le 1.0 $$ 

and

$$ AMBI_{min} = 3.083 – 0.111 * salinity, AMBI_{min} \ge 0 $$

and *N* is the number of species.

## Norwegian indices

Similarly to the [Danish indices](#danish-indices), The *Norwegian Quality Index* 
*[(NQI1)](#NQI1)* is based on modifying the *AMBI* index to local conditions
(@BORJA200742, @Rygg2013). *NQI1* is intercalibrated with other countries in 
the *North East Atlantic Geographical Intercalibration Group (NEAGIG)* (@Borgersen2019).

The other Norwegian indices *[NSI](#nsi)* and *[ISI](#isi)* are not based on 
modifying the *AMBI* index. They do employ a similar approach where each species or 
taxa is assigned an individual index score which reflects the relative sensitivity
of the species to disturbance. Then the combined average score of the index values
for a sample show the level of disturbance indicated by the species composition.

The species-specific sensitivity values for *NSI* and *ISI* are derived from 
analyses of large datasets from Norwegian monitoring data, calculating 
*Hurlbert diversity index* ([ES](#es)) values for many samples. The weighted 
averages of ES values were then calculated for each species across the samples 
where they occurred. So, species occurring more often in samples having lower 
diversity will have a lower index value.

### NQI1

The `NQI1()` function is calculated according to this formula:

$$ NQI_1 =  \begin{bmatrix} 0.5* \left( 1- \frac{AMBI}{7} \right) + 0.5 * \left(\frac{\begin{bmatrix} \frac{ln(S)}{ln(ln(N))} \end{bmatrix}  }{2.7} \right) * \left( \frac{N}{N+5} \right) \end{bmatrix} $$

where $S$ is the number of species and $N$ is the number of individuals. 

@Rygg2013 also developed an alternative index *NQI2* which is not yet included in the package.

### NSI

The *NSI* index was developed as an alternative to *AMBI* for application in 
Norwegian coastal areas (@Rygg2013)

The `NSI()` calculation method:

$$ NSI = \sum_i^S {\begin{bmatrix} \frac{N_i * NSI_i}{N_{NSI}} \end{bmatrix} } $$

### ISI

The oldest Norweigan index, the *Indicator Species Index (ISI)* does not use 
counts of individuals of each species but is based purely on *presence* 
for different species, combined with a species-specific index reflecting sensitivity
to disturbance (@Rygg2002).

$$ ISI = \sum_i^S {\begin{bmatrix} \frac{ISI_i}{S_{ISI}} \end{bmatrix} } $$

## Others

So far, the only other index included here is the *Hurlbert diversity index* (`ES()`).

### ES

The Hurlbert diversity index estimates the expected species diversity for a given
subsample size from a larger population [@Hurlbert]. *ES100* is the expected species
diversity where a subsample of 100 individuals is taken from a larger sample 
population. Obviously, if the sample contains fewer than 100 individuals, then it is 
**not** possible to take a subsample of 100 individuals. See @Hurlbert for more information.

Analysis of *ES100* across large Norwegian monitoring datasets forms the basis for the 
species-specific index values used by the [ISI](#isi) and [NSI](#nsi) indices.

### Missing indices?

Is there an index which is missing? Do you have suggestions for other index 
calculations which could be included in a future version of the `ambiR` package?
Then you are very welcome to [contribute](https://niva-denmark.github.io/ambiR/CONTRIBUTING.html)
directly or to make a new [feature request](https://github.com/NIVA-Denmark/ambiR/issues).


## References
