#' Calculates DKI (v1)
#'
#' @description
#' Calculates the Danish quality index DKI (v1)
#'
#' The function uses an estimated maximum value of H' `H_max` in Danish waters
#' as a reference value to normalise DKI.
#'
#' @details
#' The [AMBI()] and [Hdash()] functions take a dataframe of observations as an
#' argument. The DKI functions, [DKI2()] and [DKI()], do *not* take a dataframe
#' as an argument. Instead they take values of the input parameters, either
#' single values or as vectors.
#'
#' To calculate DKI for a dataframe of `AMBI` values, it could be called from
#' e.g. within a [dplyr::mutate()] function call. See the examples below.
#'
#' @seealso
#' DKI v1 has been superceded by [DKI2()] a salinity-normalised version of DKI.
#'
#' @source
#' The Danish quality index is described in:
#'
#' Carstensen, J., Krause-Jensen, D., Josefson, A. (2014) Development and testing
#' of tools for intercalibration of phytoplankton, macrovegetation and benthic
#' fauna in Danish coastal areas. Scientific Report from DCE – Danish Centre for
#' Environment and Energy No. 93. <https://dce2.au.dk/pub/SR93.pdf>
#'
#' Reference for default value of _H_max = 5_:
#'
#' _"However, in the present exercise, the Danish method used Hmax (∼5)
#' as a kind of reference"_
#'
#' Borja, A., Josefson, A.B., Miles, A., Muxika, I., Olsgaard, F., Phillips, G.,
#' Rodríguez, J.G. & Rygg, B. 2007: An approach to the intercalibration of benthic
#' ecological status assessment in the North Atlantic ecoregion, according
#' to the European Water Framework Directive. - Marine Pollution Bulletin 55:42-52.
#' <https://doi.org/10.1016/j.marpolbul.2006.08.018>
#'
#' @param AMBI        AMBI, the AZTI Marine Biotic Index, calculated using [AMBI()]
#' @param H           H', the Shannon diversity index, calculated using [Hdash()]
#' @param N           number of individuals - generated by both [AMBI()] and [Hdash()]
#' @param S           number of species - generated by both [AMBI()] and [Hdash()]
#' @param H_max       maximum H' used to normalise AMBI, _default 5_
#'
#' @return
#' `DKI` index value
#'
#' @examples
#'
#' # Simple example
#'
#' DKI(AMBI = 1.61, H = 2.36, N = 25, S = 6)
#'
#'
#' # ------ Example workflow for calculating DKI from species counts ----
#'
#' # calculate AMBI index
#' dfAMBI <- AMBI(test_data, by = c("station"), var_rep="replicate")[["AMBI"]]
#'
#' # show AMBI results
#' dfAMBI
#'
#' # calculate DKI from AMBI results
#' dplyr::mutate(dfAMBI, DKI = DKI(AMBI, H, N, S))
#'
#' @export

DKI <- function(AMBI, H, N, S, H_max=5){
  # DKI v1
  term_AMBI <- (1 - (AMBI  / 7))
  term_NS <- ((1 - (1/N)) + (1 - (1/S))) * 0.5
  DKI <- 0.5*(term_AMBI + (H/H_max)) * term_NS
  return(DKI)
}
