#' Calculates DKI (v2), the revised Danish Quality Index
#'
#' @description
#' [DKI2()] calculates a salinity-normalised version of the Danish quality
#' index (DKI) [(Carstensen et al., 2014)](#references)
#'
#' The *DKI* index is based on AMBI and can only be calculated after first calculating
#' *AMBI*, the AZTI Marine Biotic Index, and *H'*, the Shannon diversity index.
#' Both indices are included in output from the function [AMBI()].
#'
#' This function uses linear relationships between salinity and limits for `AMBI`
#' and `Hdash` to normalise the index. This is done to account for expected
#' lower species diversity in regions with lower salinity.
#'
#' Since the index is normalised to salinity, the function also requires
#' measured or estimated salinity `psal` as an argument.
#'
#' @references
#' Carstensen, J., Krause-Jensen, D., Josefson, A. (2014). "Development and testing of tools for intercalibration of phytoplankton, macrovegetation and benthic fauna in Danish coastal areas." Aarhus University, DCE – Danish Centre for Environment and Energy, 85 pp. _Scientific Report from DCE – Danish Centre for Environment and Energy_ No. 93.
#' <https://dce2.au.dk/pub/SR93.pdf>
#'
#' @details
#' The [AMBI()] and [Hdash()] functions take a dataframe of observations as an
#' argument. The *DKI* functions, [DKI2()] and [DKI()], do *not* take a dataframe
#' as an argument. Instead they take values of the input parameters, either
#' single values or as vectors.
#'
#' To calculate DKI for a dataframe of `AMBI` values, it could be called from
#' e.g. within a [dplyr::mutate()] function call. See the examples below.
#'
#' @seealso
#' For more details, see`vignette("other-indices").
#' * [DKI()] calculate DKI using the original method
#' * [AMBI_sal()] minimum AMBI for normalisation _= f(salinity)_
#' * [H_sal()] maximum H' for normalisation _= f(salinity)_
#'
#'
#' @param AMBI        AMBI, the AZTI Marine Biotic Index, calculated using [AMBI()]
#' @param H           H', the Shannon diversity index, calculated using [Hdash()]
#' @param N           number of individuals - generated by both [AMBI()] and [Hdash()]
#' @param psal        salinity
#'
#' @return
#' `DKI` index value
#'
#' @examples
#'
#' # Simple example
#'
#' DKI2(AMBI = 1.61, H = 2.36, N = 25, psal = 21.4)
#'
#'
#' # ------ Example workflow for calculating DKI (v2) from species counts ----
#'
#' # calculate AMBI index
#' df <- AMBI(test_data_DK, by = c("station"), var_rep = "sample")[["AMBI"]]
#'
#' # modify names which were not recognized by AMBI() and recalculate
#' df_obs <- dplyr::mutate(test_data_DK, species = gsub(" indet\\.", "", species))
#' df <- ambiR::AMBI(df_obs, by = c("station"), var_rep="sample")[["AMBI"]]
#'
#' # show AMBI results
#' df
#'
#' # add salinity values - these are realistic but invented values
#' df$psal <- c(21.3, 26.5)
#'
#' # calculate DKI from AMBI results
#' df <- dplyr::mutate(df, DKI=DKI2(AMBI, H, N, psal))
#'
#' dplyr::select(df, station, AMBI, H, N, psal, DKI)
#'
#' @export

DKI2 <- function(AMBI, H, N, psal){

  AMBI_sal <- AMBI_sal(psal)
  H_sal <- H_sal(psal)
  term_AMBI <- (1 - ((AMBI - AMBI_sal) / 7))
  term_H <- H/H_sal
  term_H <- ifelse(term_H > 1, 1, term_H)
  DKI2 <- 0.5*(term_AMBI + term_H) * (1 - (1/N))
  return(DKI2)
}

